### ISSUE TITLE
Fails pylint with many warnings and errors

### ISSUE THREAD

**Issue by freimer** [awslabs/aws-appflow-custom-connector-python#5]
I realize there are a lot of choices when it comes to formatting Python code and linting.  That said, pylint is fairly standard.  Current code fails with many warnings and errors.  Suggest using something like Black to clean up the formatting, and looking into the errors reported.  I could of course run this through Black myself and submit a PR, but the amount of changes would be tremendous.  Happy to do so if it will be accepted, but I'm thinking that is something the core team would prefer to do.

**Comment by freimer** [comment]
Created the pull request.  Most/all of the linting errors that remain are in the tests, which fail.  Not sure if the tests were created before changes to the code and not updated, but this is where most of the issue are.  And it is not just a "lint" issue, the tests won't run.  See for example a small snippet:
```
aws-appflow-custom-connector-python$ python -m unittest custom_connector_sdk.test.configuration_handler_tests
..EEF..EE...EEE.
======================================================================
ERROR: test_create_describe_connector_configuration_response_with_optional_parameters (custom_connector_sdk.test.configuration_handler_tests.ConfigurationHandlerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freimer/github/awslabs/aws-appflow-custom-connector-python/custom_connector_sdk/test/configuration_handler_tests.py", line 137, in test_create_describe_connector_configuration_response_with_optional_parameters
    o_auth_2_defaults = OAuth2Defaults(['a'], ['b'], ['c'], [OAuth2GrantType.CLIENT_CREDENTIALS], ['e'], ['f'])
TypeError: __init__() takes from 4 to 5 positional arguments but 7 were given

======================================================================
ERROR: test_create_describe_connector_configuration_response_with_required_parameters (custom_connector_sdk.test.configuration_handler_tests.ConfigurationHandlerTests)
Tests that a DescribeConnectorConfigurationResponse can be created with only required parameters.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/freimer/github/awslabs/aws-appflow-custom-connector-python/custom_connector_sdk/test/configuration_handler_tests.py", line 121, in test_create_describe_connector_configuration_response_with_required_parameters
    encoded_response = response.to_json()
AttributeError: 'DescribeConnectorConfigurationResponse' object has no attribute 'to_json'
```
This is way too much to fix in this one issue, so I'm requesting the PR be accepted after review and additional issues created.

**Comment by freimer** [comment]
This was merged, closing.
